openapi: 3.0.1
info:
  title: Invalid Schema
  description: An invalid schema to test OpenAPI validation
  version: "1.0.0"
paths:
  /pets:
    get:
      # Missing required operationId
      responses:
        # Invalid response code
        20x:
          description: Invalid response
          content:
            application/json:
              schema:
                type: 'invalid-type'