openapi: 3.0.1
info:
  title: Sample API
  description: A sample API to test client generation with small-openapi-codegen
  version: 1.0.0
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      responses:
        200:
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: Create a pet
      operationId: createPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        201:
          description: Pet created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        400:
          description: Invalid input
      x-codegen-request-body-name: request
  /pets/{pet_id}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      parameters:
        - name: pet_id
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Pet found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        404:
          description: Pet not found
    put:
      summary: Update a pet
      operationId: updatePet
      parameters:
        - name: pet_id
          in: path
          required: true
          description: The id of the pet to update
          schema:
            type: integer
            format: int64
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        200:
          description: Pet updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        400:
          description: Invalid input
      x-codegen-request-body-name: request
    delete:
      summary: Delete a pet
      operationId: deletePet
      parameters:
        - name: pet_id
          in: path
          required: true
          description: The id of the pet to delete
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: Pet deleted
        404:
          description: Pet not found
  /pets/photo:
    post:
      summary: Upload a photo for a pet
      operationId: uploadPetPhoto
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - pet_id
                - photo
              properties:
                pet_id:
                  type: integer
                  format: int64
                photo:
                  type: string
                  format: binary
      responses:
        200:
          description: Photo uploaded
        400:
          description: Invalid input
      x-codegen-request-body-name: request
components:
  schemas:
    Pet:
      type: object
      description: A pet
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string