openapi: 3.0.1
info:
  title: Sample API
  description: A sample API to test client generation with small-openapi-codegen
  version: 1.0.0
servers:
  - url: /v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      responses:
        200:
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: Create a pet
      operationId: createPet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        201:
          description: Pet created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        400:
          description: Invalid input
      x-codegen-request-body-name: request
  /pets/{pet_id}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      parameters:
        - name: pet_id
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Pet found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        404:
          description: Pet not found
    put:
      summary: Update a pet
      operationId: updatePet
      parameters:
        - name: pet_id
          in: path
          required: true
          description: The id of the pet to update
          schema:
            type: integer
            format: int64
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        200:
          description: Pet updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        400:
          description: Invalid input
      x-codegen-request-body-name: request
    delete:
      summary: Delete a pet
      operationId: deletePet
      parameters:
        - name: pet_id
          in: path
          required: true
          description: The id of the pet to delete
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: Pet deleted
        404:
          description: Pet not found
  /pets/{pet_id}/form:
    put:
      summary: Update a pet with form data
      operationId: updatePetWithForm
      parameters:
        - name: pet_id
          in: path
          required: true
          description: The id of the pet to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Name of the pet
                status:
                  type: string
                  description: Status of the pet
      responses:
        200:
          description: Pet updated
        400:
          description: Invalid input
      x-codegen-request-body-name: formData
  /pets/photo:
    post:
      summary: Upload a photo for a pet
      operationId: uploadPetPhoto
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - pet_id
                - photo
              properties:
                pet_id:
                  type: integer
                  format: int64
                photo:
                  type: string
                  format: binary
      responses:
        200:
          description: Photo uploaded
        400:
          description: Invalid input
      x-codegen-request-body-name: request
  /pets/photos:
    post:
      summary: Upload multiple photos for a pet
      operationId: uploadPetPhotos
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - pet_id
                - photos
              properties:
                pet_id:
                  type: integer
                  format: int64
                photos:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        200:
          description: Photos uploaded
        400:
          description: Invalid input
      x-codegen-request-body-name: request
components:
  schemas:
    Address:
      type: object
      description: An address
      required:
        - street
        - city
      properties:
        street:
          type: string
          description: Street address
        city:
          type: string
          description: City name
        state:
          type: string
          description: State or province
        zipCode:
          type: string
          description: Postal code
    Pet:
      type: object
      description: A pet
      required:
        - id
        - name
        - details
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        species:
          type: string
          description: Type of animal
        weight:
          type: number
          format: float
          description: Weight in kilograms
        owner:
          type: object
          description: The owner of the pet (optional)
          required:
            - name
            - id
          properties:
            id:
              type: integer
              format: int64
              description: The owner's ID
            name:
              type: string
              description: The owner's name
            phone:
              type: string
              description: The owner's phone number
            email:
              type: string
              format: email
              description: The owner's email address
            address:
              $ref: '#/components/schemas/Address'
        details:
          type: object
          description: Required details about the pet
          required:
            - breed
          properties:
            breed:
              type: string
              description: The breed of the pet
            birthDate:
              type: string
              format: date
            color:
              type: string
              description: Pet's color